### ISSUE TITLE
Check SMS availability is causing API issues

### ISSUE THREAD

**Issue by danpal** [ethitter/Authy-for-WP#11]
https://github.com/ethitter/Authy-for-WP/blob/master/authy-wp.php#L403

This actually requests an SMS be sent to Authy user ID 1. This is causing some troubles for the API (logging, reporting etc). 
Currently there is no way to detect if SMS is or not enabled. If this is necessary we could create an end-point for it,  otherwise it's probably best to remove this check as it's causing trouble.

**Comment by ethitter** [comment]
@danpal, I disabled the check in 3dbd652. 

It would be great if the API could provide a way to check SMS availability. Not sure what other features you have in mind for the future, but a general "API key supported features" method could be a smart approach, since it would provide a generic way to check what the given API key is capable of doing on Authy's end.

**Comment by danpal** [comment]
We could build an endpoint to provide the current plan and capabilities. We'll talk about the design today and we'll share more later. We can probably have it on production by end of next week.

**Comment by ethitter** [comment]
Excellent. Depending on what is included in the new endpoint, we may be able to address #9 as well.

**Comment by danpal** [comment]
OK we are bringing an end-point to Authy in the next few weeks. The enpoint will return an XML or JSON object with the following information:

app name: The name the user choose.
current plan: Sandbox, Small, Medium, Large.
sms enabled: Yes if the account can send SMS, no otherwise.
is white label: This is enterprise plans.
stats: SMS sent, # of logins etc.

**Comment by danpal** [comment]
Hey @ethitter we just finished this, take a look at:

http://docs.authy.com/#section-Application_Details

Is this enough?
