### ISSUE TITLE
Provide option to block authentication via XML-RPC and APP requests

### ISSUE THREAD

**Issue by ethitter** [ethitter/Authy-for-WP#15]
If enabled, this option will require that users log in directly in WordPress. It will also prevent use of the mobile apps and any third-party authenticated interactions with WordPress.

Requested by way of http://wordpress.org/support/topic/there-needs-to-be-an-option-to-disallow-non-authy-logins

**Comment by Leopere** [comment]
On further inspection it only required the authy token for hitting the dashboard but posting I didnt need it.
